[tool.poetry]
name = "basic-textual"
version = "0.1.0"
description = ""
authors = ["camilo andrade"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
textual = "^0.85.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
